<a href="https://colab.research.google.com/github/Sillians/AI-Saturday-Deep-Learning-Cohort-6/blob/main/NumPy_refresher_and_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy refresher 

In [ ]:
import numpy as np

## Scalars

In [ ]:
a = np.array(2)
a = a + 2
print(a, a.shape)

4 ()


## Vectors

In [ ]:
b = np.array([1, 2, 3, 4])
print(b, b.shape)

[1 2 3 4] (4,)


In [ ]:
b.shape = (4, 1)
b

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
c = b
print(c)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
print(b.T.dot(c))

[[30]]


In [ ]:
z = b.T.dot(c)
print(z.shape)

(1, 1)


## Matrices

In [ ]:
b.shape = (4, 1)
b

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
c = b.transpose()
c

array([[1, 2, 3, 4]])

In [ ]:
b.dot(c)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [ ]:
np.multiply(b, c)          # b*c

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [ ]:
b@c          # b.c

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [ ]:
a = [1,2,3]
m = np.array([[[a, a, a], [a, a, a]], [[a, a, a], [a, a, a]]])
print(m.shape)

(2, 2, 3, 3)


## Tensors

In [ ]:
np.array([[[13, 56], [13, 56], [34, 17]], [[13, 56], [13, 56], [34, 17]]]).shape

(2, 3, 2)

In [ ]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print(t, t.shape)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]] (3, 3, 2, 1)


## Element-wise Matrix Operations

In [ ]:
# Scaling

m = t*134
print(m.shape)

(3, 3, 2, 1)


In [ ]:
m = m/255
print(m)

[[[[0.5254902 ]
   [1.05098039]]

  [[1.57647059]
   [2.10196078]]

  [[2.62745098]
   [3.15294118]]]


 [[[3.67843137]
   [4.20392157]]

  [[4.72941176]
   [5.25490196]]

  [[5.78039216]
   [6.30588235]]]


 [[[6.83137255]
   [7.35686275]]

  [[7.88235294]
   [8.40784314]]

  [[8.93333333]
   [8.93333333]]]]


In [ ]:
# Adding matrices (MUST be the same shape)
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([[1, 2]])
b

array([[1, 2]])

In [ ]:
print(a*b)

[[1 4]
 [3 8]]


In [ ]:
print(np.multiply(a, b))

[[1 4]
 [3 8]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]]) # -> 2x3
b = np.array([[1, 2], [3, 4], [5, 6]]) # -> 3x2
# np.multiply(a,b)

np.matmul(a, b)
# a.dot(b)
# a@b

array([[22, 28],
       [49, 64]])

## Matrix Multiplication

For an *NxM* matrix:
- Number of columns in N MUST be equal to number of rows in M.
- The output will have shape of (number rows in N) X (number of columns in M).
- Order matters. Multiplying NxM is not the same as multiplying MxN.
- Data in N should be arranged as rows, while data in M should be arranged as columns. It is very important in NN because as we go through each layer, we want to reduce the number of features (columns) in the input, and still maintain the number of examples (rows).

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a, a.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b, b.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [ ]:
c = np.matmul(a, b)
print(c, c.shape)

[[ 70  80  90]
 [158 184 210]] (2, 3)


### NumPy's dot function
You may sometimes see NumPy's dot function in places where you would expect a matmul. It turns out that the results of dot and matmul are the same if the matrices are two dimensional.

In [ ]:
a = np.array([[1,2],[3,4]])
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [ ]:
np.matmul(a, a)

array([[ 7, 10],
       [15, 22]])

## Transpose

In [ ]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

NumPy does this without actually moving any data in memory - it simply changes the way it indexes the original matrix - so it’s quite efficient.

However, that also means you need to be careful with how you modify objects, because they are sharing the same data. For example, with the same matrix m from above, let's make a new variable m_t that stores m's transpose. Then look what happens if we modify a value in m_t:

In [ ]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [ ]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

So remember to consider the transpose just as a different view of your matrix, rather than a different matrix entirely.

### A real use case
Let's say you have the following two matrices, called inputs and weights,

In [ ]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
print(inputs, inputs.shape)

[[-0.27  0.45  0.64  0.31]] (1, 4)


In [ ]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
print(weights, weights.shape)

[[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]] (3, 4)


In [ ]:
weights.T.shape

(4, 3)

In [ ]:
# np.matmul(inputs, weights)
# inputs.dot(weights)

In [ ]:
np.matmul(inputs, weights.T).shape

(1, 3)

In [ ]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

## Assignment

In [ ]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([[2,3,5,7,9]])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    min_arr = np.min(input_array)
    sub_arr = np.subtract(input_array, min_arr)
    inputs_minus_min = sub_arr

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    max_arr = np.max(inputs_minus_min)
    div_arr = np.divide(inputs_minus_min, max_arr)
    inputs_div_max = div_arr

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    a = m1.shape[1]
    b = m2.shape[0]
    if a != b:
        return False
    # a*b for a,b in (m1,m2)
    # pass


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    else:
        return m1.dot(m2)
    # pass
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)
    # pass


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[2 3 5 7 9]]
Input minus min: [[0 1 3 5 7]]
Input  Array: [[0.         0.14285714 0.42857143 0.71428571 1.        ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
False
Mean == 2.6666666666666665
